"""Initial content for the `suggested_questions` table.

Only used once, the first time the app starts against an empty table (see
`db.py::_seed_suggestions_if_empty`) — after that this list is never read
again; the table itself is the source of truth.
"""

CATEGORIES = ["semplice", "piccante", "esplicito"]

SEED_SUGGESTIONS: dict[str, list[str]] = {
    "semplice": [
        "Chi di noi ordinerebbe la pizza con l'ananas o qualche combinazione di ingredienti totalmente illegale?",
        "Chi si addormenta sul divano dopo esattamente cinque minuti dall'inizio di qualsiasi film?",
        "Chi è quello che non sa mai decidere cosa ordinare e fa perdere mezz'ora per scegliere un ristorante?",
        "Chi ha la suoneria del telefono più imbarazzante o tiene il volume delle notifiche sempre a palla?",
        "Chi arriverebbe in ritardo persino al proprio compleanno?",
        "Chi ha la macchina che sembra un magazzino mobile, tra cianfrusaglie, bottiglie vuote e oggetti accumulati nel tempo?",
        "Chi perde costantemente le chiavi di casa, il portafoglio o il cellulare (spesso mentre lo tiene in mano)?",
        "Chi è il re o la regina dei selfie venuti male, con espressioni facciali completamente assurde?",
        "Chi passa ore a guardare video di gattini o reel scemi su Instagram la sera prima di dormire?",
        "Chi ha la risata più contagiosa o strana del gruppo, quella che fa ridere tutti anche senza sapere il motivo?",
        "Chi è il cuoco del gruppo che si vanta di fare piatti stellati ma finisce per bruciare pure l'acqua della pasta?",
        "Chi ha la collezione di meme più infinita nella galleria del telefono ed è pronto a usarla in ogni chat?",
        "Chi si agita di più e va in panico totale quando il Wi-Fi salta o manca la connessione?",
        "Chi è l'esperto indiscusso di serie TV che le ha viste tutte, ma proprio tutte?",
        "Chi ha l'abitudine di cantare a squarciagola in macchina come se fosse a un concerto negli stadi?",
        "Chi è quello che a una festa attacca bottone persino con i muri e conosce tutta la storia della gente?",
        "Chi si lamenta continuamente del freddo o del caldo estremo, indipendentemente dalla stagione?",
        "Chi ha la mania dell'ordine e non tollera neanche una sedia fuori posto o un quadro storto?",
        "Chi è l'eterno ottimista del gruppo che vede il bicchiere sempre mezzo pieno anche nelle situazioni più assurde?",
        "Chi ha la battuta pronta (o la pessima battuta da boomer) che fa calare il gelo ma fa ridere lo stesso?",
        "Chi non resiste a un dolce o a una porzione extra di cibo neanche se è letteralmente pieno?",
        "Chi è quello che fa più foto e video a qualsiasi cosa pur di immortalare ogni singolo secondo?",
        "Chi ha l'orientamento peggiore e riuscirebbe a perdersi pure usando il navigatore con la voce guida?",
        "Chi si veste sempre e solo con i soliti colori neutri (nero, grigio, blu) perché odia cambiare stile?",
        "Chi è il collezionista seriale di cianfrusaglie, fumetti, carte o oggetti inutili ma bellissimi?",
        "Chi ha la scusa pronta più creativa e fantasiosa per dare buca a un impegno che non ha voglia di fare?",
        "Chi è quello che quando beve due gocce di alcol in più inizia a fare discorsi filosofici profondissimi?",
        "Chi ha l'ansia da prestazione prima di fare una semplice telefonata per ordinare l'asporto?",
        "Chi dimentica sistematicamente i compleanni di tutti e si giustifica all'ultimo secondo?",
        "Chi è il più tecnologico del gruppo, quello a cui tutti chiedono aiuto quando il computer non funziona?",
        "Chi ha la fobia inspiegabile per qualche insetto innocuo, tipo le farfalle o le formiche?",
        "Chi passa più tempo a scegliere il filtro giusto per una foto che a viverne il momento?",
        "Chi è quello che si commuove o ha gli occhi lucidi guardando un cartone animato o una pubblicità tenera?",
        "Chi ha sempre in tasca una caramella, una gomma da masticare o fazzoletti da offrire agli altri?",
        "Chi fa i regali più azzeccati, originali e pensati di tutto il gruppo?",
        "Chi è l'insicuro cronico che chiede sempre \"Ma come sto?\" prima di uscire di casa?",
        "Chi ha la voce più squillante e si fa sentire in mezzo a una piazza affollata senza microfono?",
        "Chi è il fan numero uno di qualche genere musicale totalmente di nicchia o improbabile?",
        "Chi fa più fatica a svegliarsi la mattina e ha bisogno di almeno cinque sveglie messe a distanza di dieci minuti?",
        "Chi è quello che legge le recensioni di qualsiasi cosa (dal ristorante al frullatore su Amazon) prima di comprare o prenotare?",
        "Chi ha sempre un aneddoto divertente o una storia assurda da raccontare per ravvivare la conversazione?",
        "Chi è il più pantofolaio del gruppo che preferirebbe una serata sul divano a qualsiasi festa mondana?",
        "Chi si vanta di avere una memoria di ferro ma poi non si ricorda cosa ha mangiato a pranzo?",
        "Chi ha la tendenza a comprare piante d'appartamento e farle morire tutte nel giro di due settimane?",
        "Chi è quello che fa più domande durante un film, chiedendo \"Ma questo chi è?\" ogni dieci minuti?",
        "Chi ha la camminata più riconoscibile da lontano, al punto che lo si riconosce solo da come muove i passi?",
        "Chi è il re degli acquisti compulsivi su internet a notte fonda?",
        "Chi ha la battuta fulminante pronta quando c'è un momento di imbarazzo generale?",
        "Chi è quello che custodisce i segreti più teneri o i diari d'infanzia più imbarazzanti?",
        "Chi di noi, in fondo in fondo, è il collante che riesce sempre a tenere unito questo gruppo?",
    ],
    "piccante": [
        "Chi di noi è il più desiderato o fa segretamente più gola agli altri componenti del gruppo?",
        "Se foste costretti a tradire il vostro partner attuale con qualcuno seduto in questa stanza, chi scegliereste senza esitare?",
        "Se doveste scegliere un solo membro del gruppo con cui fare un'esperienza trasgressiva o un gioco a tre, chi sarebbe il primo della lista?",
        "Chi di noi, sotto sotto, ha flirtato o ci ha provato spudoratamente (anche solo con gli sguardi o i messaggi) con il/la partner di un altro del gruppo?",
        "Se dovete pensare a chi di noi ha il passato sessuale più scandaloso, promiscuo o fuori dagli schemi, su chi puntereste tutti i soldi?",
        "Chi tra di noi ha la più alta proabilità di cedere alla tentazione se ci fosse un'occasione di sesso occasionale o di scambismo tra amici?",
        "Se doveste scegliere una persona del gruppo da chiudere in una stanza per un'ora solo per vedere cosa succederebbe, chi scegliereste?",
        "Guardando tutti i presenti: chi di noi ha la chimica più forte e innegabile con qualcun altro del gruppo, anche se fate finta di niente?",
        "Se stasera ci fosse un'occasione di trasgressione totale e senza regole, chi sarebbe il primo a dire di sì e chi invece farebbe il prezioso tirandosi indietro?",
        "Chi del gruppo ha il potenziale nascosto più esplosivo a letto, quello che nessuno immaginerebbe mai guardandolo di giorno?",
        "Chi di noi ha il magnetismo o il sex appeal più forte, capace di catalizzare l'attenzione di tutti quando entra in una stanza?",
        "Se doveste scommettere su chi ha avuto più \"avventure\" segrete con persone della vostra comitiva allargata o conoscenti in comune, su chi puntereste?",
        "Chi tra di noi subisce più di tutti il fascino del \"proibito\" all'interno del gruppo?",
        "Se si dovesse formare una coppia clandestina segreta tra due persone di questo gruppo, chi farebbe la prima mossa?",
        "Chi di noi ha lo sguardo o il modo di fare che fa arrossire o imbarazzare di più gli altri senza neanche farlo apposta?",
        "Chi del gruppo, se ci fosse un tasso alcolemico altissimo a fine serata, finirebbe per bacendersi con un altro dei presenti?",
        "Chi tra di noi ha la nomea di essere quello che flirta di più con chiunque, ma in realtà non conclude mai nulla?",
        "Se doveste scegliere un compagno o una compagna di viaggio per un weekend trasgressivo in un motel fuori città tra i presenti, chi escludereste subito e chi portereste?",
        "Chi di noi ha la gelosia più marcata o nascosta nei confronti delle attenzioni che gli altri ricevono?",
        "Chi del gruppo fa più strage di cuori (o di letti) fuori da qui, ma nel gruppo fa il santo?",
        "Chi tra di noi ha un passato o un presente di \"amicizie con i benefici\" che nessuno nel gruppo conosce nei dettagli?",
        "Se un ex partner di uno di noi dovesse riapparire e fare una mossa, con chi del gruppo ci sarebbe più tensione o rischio di un ritorno di fiamma?",
        "Chi di noi ha la capacità di capire subito chi piace a chi all'interno della comitiva, muovendosi come un burattinaio?",
        "Chi del gruppo ha fatto battere il cuore (o scatenare pensieri impuri) a più persone diverse nel corso degli anni?",
        "Se doveste scegliere una persona del gruppo da cui farsi sedurre consapevoli di cascarci in pieno, chi sarebbe?",
        "Chi di noi ha il fascino più ambizioso e manipolatore quando vuole ottenere l'attenzione di qualcuno che gli interessa?",
        "Chi del gruppo ha la tendenza a creare più dinamiche di tensione sessuale non risolta durante le serate?",
        "Chi tra di noi è quello che verrebbe \"puntato\" per primo se foste tutti single in un locale affollato?",
        "Se doveste scegliere una persona del gruppo con cui fare un lento ravvicinato o un ballo provocante senza che nessuno dica nulla, chi scegliereste?",
        "Chi di noi ha le fantasie più spinte che ruotano proprio attorno alle persone sedute a questo tavolo?",
        "Chi del gruppo ha un modo di vestirsi o di muoversi che calibra perfettamente per risultare provocante senza dar nell'occhio?",
        "Chi tra di noi ha tradito o rischiato di tradire il proprio partner storico proprio con qualcuno che gravita attorno al vostro giro?",
        "Se si dovesse eleggere il \"re\" o la \"regina\" indiscussa del flirt e della provocazione tra amici, chi vincerebbe a mani basse?",
        "Chi di noi ha l'energia sessuale più evidente, quella che si percepisce anche quando sta semplicemente in silenzio?",
        "Chi del gruppo ha un ascendente così forte sugli altri che potrebbe convincere chiunque a fare una pazzia?",
        "Se doveste indovinare chi tra di noi ha ricevuto più proposte indecenti o messaggi spinti da sconosciuti nell'ultimo mese, su chi puntereste?",
        "Chi tra di noi ha un rapporto di sguardi o di intesa fisica sotterranea con qualcun altro che va avanti da anni?",
        "Chi del gruppo farebbe la figura del geloso cronico se il proprio partner attuale guardasse un po' troppo un altro dei presenti?",
        "Se ci fosse una regola che permette a tutti di scambiarsi il partner per una notte all'interno del gruppo, chi creerebbe il panico generale con le sue scelte?",
        "Chi di noi ha la fama di essere un rubacuori impunito, collezionando storielle e flirt a intermittenza?",
        "Chi del gruppo è quello che sotto i colpi dell'alcol diventa improvvisamente molto più fisico, espansivo e \"pericoloso\"?",
        "Se doveste scegliere una persona del gruppo da cui non vi fareste mai toccare neanche per scherzo, chi sarebbe?",
        "Chi tra di noi ha l'istinto più predatorio quando punta una persona che gli interessa in una festa o in un locale?",
        "Chi del gruppo ha la percentuale più alta di ex storici che ancora oggi rosicano o sperano in un ritorno?",
        "Se doveste identificare la persona del gruppo che ha più scheletri nell'armadio legati a triangoli amorosi, chi scegliereste?",
        "Chi di noi ha un'aria così sfuggente e misteriosa da alimentare le fantasie più spinte degli altri?",
        "Chi del gruppo ha l'abitudine di testare i propri limiti giocando con il fuoco e flirtando sul filo del rasoio?",
        "Se doveste scommettere su chi ha provato un'attrazione fisica passeggera per tutti i membri del gruppo almeno una volta, su chi puntereste?",
        "Chi tra di noi ha la battuta o il doppio senso sempre pronto per creare imbarazzo e tensione sessuale nell'aria?",
        "Se si aprisse ufficialmente il dibattito su chi è il perno invisibile di tutte le attrazioni e le dinamiche segrete del gruppo, chi verrebbe indicato all'unanimità?",
    ],
    "esplicito": [
        "Chi farebbe sesso proprio stasera se glielo chiedessi?",
        "Chi ha la fantasia sessuale più spinta mai avuta?",
        "Chi ha il desiderio sessuale più insaziabile del gruppo?",
        "Chi ha già avuto un rapporto a tre o più?",
        "Chi guarda contenuti per adulti più spesso di quanto ammetta?",
        "Chi ha avuto l'orgasmo più intenso con uno sconosciuto piuttosto che con un partner fisso?",
        "Chi ha il record di partner diversi in una sola settimana?",
        "Chi si eccita più facilmente di tutti?",
        "Chi farebbe una serata a luci rosse senza pensarci due volte?",
        "Chi ha fatto sesso lo stesso giorno in cui ha conosciuto la persona?",
        "Chi ha la fantasia di fare sesso con più persone insieme?",
        "Chi ha il rapporto sessuale più lungo mai avuto, a sentire lui/lei?",
        "Chi manderebbe un video hot se glielo chiedesse la persona giusta?",
        "Chi si definirebbe insaziabile a letto senza pensarci due volte?",
        "Chi cambierebbe partner stanotte stesso se potesse, senza pensarci?",
        "Chi ha avuto più di un rapporto nello stesso giorno?",
        "Chi ha il miglior rapporto con la propria sessualità?",
        "Chi ha avuto il weekend più intenso della propria vita sessuale?",
        "Chi ha la lista più lunga di luoghi insoliti dove ha fatto sesso?",
        "Chi si definirebbe più dominante o più sottomesso senza esitazione?",
        "Chi ha già provato qualcosa che considerava un proprio tabù personale?",
        "Chi ha un ricordo piccante che non ha mai raccontato a nessuno finora?",
        "Chi ha già avuto una serata basata solo sul desiderio, senza sentimenti coinvolti?",
        "Chi ha la reputazione più pericolosa quando flirta sul serio?",
        "Chi ha il rapporto più intenso con la propria immaginazione erotica?",
        "Chi manderebbe un messaggio audace senza pensarci se sapesse di non essere scoperto?",
        "Chi ha già avuto un incontro durato un'intera notte senza dormire?",
        "Chi ha il coraggio di ammettere la propria fantasia più nascosta in pubblico?",
        "Chi ha già avuto una storia basata solo sull'attrazione fisica?",
        "Chi ha il desiderio più forte quando si tratta di provare cose nuove a letto?",
        "Chi ha già avuto un'esperienza che gli/le ha fatto scoprire un lato di sé sconosciuto?",
        "Chi ha il magnetismo più forte quando decide seriamente di sedurre qualcuno?",
    ],
}
